#This workflow upload the databases to github packages

name: Release

on:
  push:
    branches: [master]

jobs:
  Release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Get version
      run: |
        VERSION=$( date +%y.%m.%d )
        echo "::set-env name=PACKAGE_VERSION::$VERSION"
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      
    - name: Publish release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: ${{ env.PACKAGE_VERSION }}
        prerelease: false
        title: ${{ env.PACKAGE_VERSION }}
        files: |
          ./data/dofus.fr.json
          ./data/dofus.en.json
          ./data/dofus.de.json
          ./data/dofus.es.json
          ./data/dofus.it.json
          ./data/dofus.pt.json
    
    - name: Create branch
      uses: peterjgrainger/action-create-branch@v2.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        branch: ${{ env.PACKAGE_VERSION }}
